cpp_compat    = true
header        = "// SPDX-License-Identifier: MIT"
include_guard = "STL_THUMB_H"
language      = "C"
no_includes   = true
style         = "Type"
sys_includes  = ["stdbool.h", "stdint.h"]
tab_width     = 4
